name: Accessibility Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  axe-scan:
    name: Axe Accessibility Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Install Playwright
        run: npx playwright install --with-deps chromium

      - name: Run Axe accessibility tests
        run: |
          npm install -D @axe-core/cli
          npx serve -s dist -l 8080 &
          sleep 5
          npx axe http://localhost:8080 --exit
        continue-on-error: true

  pa11y:
    name: Pa11y WCAG 2.2 AA Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run Pa11y
        run: |
          npm install -g pa11y pa11y-ci
          npx serve -s dist -l 8080 &
          sleep 5
          pa11y --standard WCAG2AA --level error http://localhost:8080
        continue-on-error: true
