name: Bundle Size Analysis

on:
  pull_request:
    branches: [main]

jobs:
  bundle-size:
    name: Bundle Size Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Analyze bundle size
        uses: preactjs/compressed-size-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          pattern: "./dist/**/*.{js,css,html}"
          exclude: "{**/*.map,**/node_modules/**}"
          minimum-change-threshold: 100

  lighthouse-budget:
    name: Performance Budget
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Check bundle size budget
        run: |
          BUNDLE_SIZE=$(du -sb dist | cut -f1)
          BUDGET=5242880  # 5MB in bytes
          echo "Bundle size: $BUNDLE_SIZE bytes"
          echo "Budget: $BUDGET bytes (5MB)"
          if [ $BUNDLE_SIZE -gt $BUDGET ]; then
            echo "❌ Bundle size exceeds budget!"
            exit 1
          else
            echo "✅ Bundle size within budget"
          fi
